### ISSUE TITLE
Top queries panel in Grafana only showing blocked queries

### ISSUE THREAD

**Issue by dlmorgan999** [avojak/pihole-influxdb-monitor#7]
This container is great - thanks so much for making it available! Having said that, I imported the Grafana dashboard, and it appears (by comparing it to the native Pi-Hole dashboard) that the Total Queries graph is displaying blocked queries, but not permitted queries.  I'm going to take a stab at fixing it myself, but I have zero experience with Flux, so I figured I'd post here as well.

Here's a screenshot of the Pi-Hole dashboard:

<img width="739" alt="image" src="https://github.com/avojak/pihole-influxdb-monitor/assets/7689947/d28453a1-bc2a-485e-a752-ff731c5be487">

And this is what I'm seeing on the Grafana dashboard:

<img width="694" alt="image" src="https://github.com/avojak/pihole-influxdb-monitor/assets/7689947/efc4eb80-eab8-4f53-b203-318645beefd4">

**Comment by avojak** [comment]
Ah - I think I know what the problem is. Could you go to the menu for the panel and click Edit. Then in query B could you try replacing the `pihole-01` with `$alias` on this line: 

```
  |> filter(fn: (r) => r["alias"] == "pihole-01")
```

One of my Pi-holes is named `pihole-01`, so it looks like I incorrectly created the dashboard template!

This is what I would expect the correct queries to look like:
<img width="892" alt="image" src="https://github.com/avojak/pihole-influxdb-monitor/assets/3663899/1fe95a0b-1b26-4c25-aa06-937d1d5e1356">

**Comment by dlmorgan999** [comment]
Yup - that fixed it.  Thanks for the quick response!
